### PR TITLE
Remove node-expat

### PR DESCRIPTION
**Pull request by sonnyp**
Let's remove node-expat until issues are fixed.
See https://github.com/node-xmpp/node-expat/issues/114

### CODE REVIEW

**Comment by sonnyp** [comment]
@lloydwatkin should I merge this?

@chris-rock @dodo @astro what do you guys think? Sorry for spamming but it's a pretty bug change.

**Comment by chris-rock** [comment]
Would it be an option to change the default behavior instead of removing? Therefore we use sax as default?

**Comment by sonnyp** [comment]
@chris-rock sax_ltx will be the default.
I prefer to remove it, no need to compile a big (native) dependency if the module isn't being used.

**Comment by chris-rock** [comment]
Alright. I am okay with it. we need to update the readme and use the proper version number.

**Comment by sonnyp** [comment]
@chris-rock you mean node-expat README? Not sure what you mean about using the proper version number.

**Comment by chris-rock** [comment]
I would like to ensure, that existing users will not have bad experience. A patch version bump may lead to errors in existing project. What do you think?

**Comment by lloydwatkin** [comment]
I think should be ok, the api isn't changing, just the internals. We could do a major if people felt that way.

**Comment by sonnyp** [comment]
@chris-rock I would take the risk, current behavior of using node-expat is known to cause errors.

**Comment by sonnyp** [comment]
I would use a major version change though yes

**Comment by chris-rock** [comment]
I leave it up to you guys. Thanks you very much for this up @sonnyp

**Comment by sonnyp** [comment]
Let's wait for this, see https://github.com/node-xmpp/node-expat/issues/114#issuecomment-95456140

**Comment by sonnyp** [comment]
closing this in favor of https://github.com/node-xmpp/ltx/pull/63

**Pull request closed without merging**
